# SPDX-License-Identifier: MIT

# Defines the build targets for the GitHub Actions workflow or local build script.
# See https://zmk.dev/docs/user-setup#build-matrix-including-shields
include:
  - board: nice_nano_v2 # Target board for the left side
    shield: skeletyl_left # Shield identifier for the left side
  - board: nice_nano_v2 # Target board for the right side
    shield: skeletyl_right # Shield identifier for the right side