manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main # Or pin to a specific ZMK version/commit if desired
      import: app/west.yml
  self:
    path: config # Tells west your config repository is in the 'config' directory